### ISSUE TITLE
Use Сalm theme as official twister theme

### ISSUE THREAD

**Issue by iHedgehog** [miguelfreitas/twister-html#110]
Hello, i'm Сalm theme developer. And i like to suggest my theme as default for twister. This theme looks more aesthetic. It has a lot of bugfixes, and several new features. People like it. =)

![1](https://f.cloud.github.com/assets/6762673/2401488/c76afea6-aa16-11e3-8945-2c9c269a9fb2.png)

![2](https://f.cloud.github.com/assets/6762673/2401489/c7722a82-aa16-11e3-8166-e97d592ae3c8.png)

![3](https://f.cloud.github.com/assets/6762673/2401487/c764138e-aa16-11e3-9985-acb8aefc5124.png)

And remember about new cool twister logo.

![4](https://f.cloud.github.com/assets/6762673/2399873/85b65dec-aa03-11e3-851b-b0f96b30a7fc.png)

Сhangelog:

- DHT indicator on main page
- names autocomplete in text area (from your followings)
- sound notifications for mentions and DMs with volume control
- language switcher
- send keys switcher
- added «back» button to DMs modal window
- different colors for links by type
- switcher between normal/promoted posts over postboard
- options page
- proper organisation of theme files
- a lot of fixes
- cool blue individual design
- all new icons drawn by me

https://github.com/iHedgehog/twister-calm

**Comment by iShift** [comment]
Official repository - twister-html have all 3 theme in one, close?
