### ISSUE TITLE
Implement web notifications

### ISSUE THREAD

**Issue by djmaze** [miguelfreitas/twister-html#169]
It would be really useful to have notifications (for new messages etc.) in the desktop environment. So twister would more seemlessly integrate into the overall desktop experience.

That's what the [Web Notifications API](http://www.w3.org/TR/notifications/) was made for in modern browsers. It should be really easy to implement, here's a [tutorial](http://www.sitepoint.com/introduction-web-notifications-api/).

**Comment by slr** [comment]
since #221 we have some kind of that, aren't we? close maybe?
