### ISSUE TITLE
"Can't connect to twister daemon" dialog with nginx subdirectory

### ISSUE THREAD

**Issue by homlett** [miguelfreitas/twister-html#224]
I'm trying to reserve a subdirectory from my domain name to twister (mydomain.com/twister/). I'm using nginx. There is an option to do this :
```
	location /twister/ {
		proxy_pass		http://127.0.0.1:28332/;
		}
```
It's working very well with all my applications, but not with twister... To be more clear, twisterd gives the html pages (with images, scripts, css, etc.), but the client side (a kind of javascript daemon?) can't connect to twisterd for making requests. There is an error dialog with "Can't connect to twister daemon". I suspect the html/js client trying to connect to the root domain, ignoring the directory in the url. So, it can't communicate with twisterd. But maybe I've wrong.
I add that I can use mydomain.com:28332 directly with no troubles.

There is some parameters we can add to nginx configuration file, like :
```
	proxy_set_header		X-Forwarded-Proto $scheme;
	proxy_set_header		X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header		Host $http_host;
	proxy_set_header		Host $host;
	proxy_set_header		Host $host:$server_port;
	proxy_set_header		X-Real-IP $remote_addr;
```
I tried them (not all in the same time of course), but no success.

FYI, a subdomain configuration works without any troubles. See https://github.com/miguelfreitas/twister-html/issues/93

Please excuse my bad English, and thanks for your help!

**Comment by homlett** [comment]
Oh, I've just found where the bug is! In `js/twister_io.js`, line number 13:
```
   var foo = new $.JsonRpcClient({ ajaxUrl: '/' });
```
I've simply replaced `{ ajaxUrl: '/' }` with `{ ajaxUrl: '/twister/' }` (for my case).
I think `{ ajaxUrl: window.location.pathname.replace(/[^\/]*$/, '') }` should fix the bug in most of situations, but I'm not developper.

And I'm sorry, I don't know git very well so I can't make a pull request. Hope this will be useful.

**Comment by Tschaul** [comment]
Hi,

I can issue a pull request. But what is the `replace` good for? Wouldn't `{ ajaxUrl: window.location.pathname }` work for you too?

Greetings

**Comment by homlett** [comment]
> I can issue a pull request.  

Great!


`{ ajaxUrl: window.location.pathname }` works only on the twister home page.

The `.replace(/[^\/]*$/, '')` part is needed to strip the page name when we are on one. For example `network.html` or `tmobile.html` but `home.html` too.

However, if tomorow there is an options directory or whatever other directory, like `/options/network.html`, this script will fail. I don't know how we can "pre-fix" that.

**Comment by Tschaul** [comment]
Ah ok
