### ISSUE TITLE
Updating profile "Save Changes" is greyed out

### ISSUE THREAD

**Issue by kenrestivo** [miguelfreitas/twister-html#263]
Profile was created, am currently logged into network, blockchain is up to date.

Went to Profile tab, tried to add a picture and update some of the info.

"Save Changes" is greyed out. The only available buttons are "Cancel" and "Secret Key".

**Comment by kenrestivo** [comment]
Force hacking it in Chrome by forcing enabled=enabled and removing the "disabled" css selector made the button work, and apparently the profile update succeeded. So the problem appears to be the CSS in the UI somewhere, sorry for not bothering to track it down any further.

**Comment by slr** [comment]
@kenrestivo problem is way too down deeper: currently we have some mess in loading of peers which we are following.

**Comment by slr** [comment]
I suppose it was solved somehow since it looks working for now. there's even popup prompt after saving added: https://github.com/miguelfreitas/twister-html/issues/317
