### ISSUE TITLE
Make Description in Profile Multiline

### ISSUE THREAD

**Issue by black-puppydog** [miguelfreitas/twister-html#277]
The "input-description" field in profile-edit.html already supports newline characters, and there's really no reason to not give users the possibility to enter them by hand, too, is there?
As a complete HTML n00b I just replaced the <input/> tag with <textarea></textarea> and I already got something usable, although obviously the style was messed up.
But anyone with a hint of HTML experience should be able to do this in a second, no?

**Comment by kseistrup** [comment]
In python it would be something like

```python
   desc = desc.replace('\n', '<br/>')
```

**Comment by slr** [comment]
ok, it's fixed via https://github.com/miguelfreitas/twister-html/commit/f8b8b777a11a76f089bf8471808c857f5640c14b and https://github.com/miguelfreitas/twister-html/commit/904c9315fcab99a3cd368c8613b099defdbe9020

**Comment by slr** [comment]
reopen until it will be merged into `master`
