### ISSUE TITLE
can not scroll down in timeline anymore (Uncaught TypeError)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [miguelfreitas/twister-html#288]
1. see pics below for the situation for user A
2. logging in with another account B: I can scroll down the timeline much more into the past (probably because B's not subscribed to the user who generates this "bad post" X for user A?)
3. unfortunately I don't see which/what X is

- chromium speaks of: Uncaught TypeError: Cannot read property 'replace' of undefined
- Qupzilla: TypeError: 'undefined' is not an object

twisterd 0.9.30
happens in newest twister-html + old NIN

please tell me if you need more info
![bildschirmfoto vom 2015-08-02 16 17 54](https://cloud.githubusercontent.com/assets/642286/9026538/a265cec2-3932-11e5-90b7-7a03b47bc040.png)

![bildschirmfoto vom 2015-08-02 16 11 57](https://cloud.githubusercontent.com/assets/642286/9026542/aa2f045c-3932-11e5-9200-249675807363.png)

**Comment by erqan** [comment]
@Erkan-Yilmaz  do you remember "#warning some of my #test messages may break your timeline.. #suggestion unfollowing me and refreshing the page should fix." ;)
unfollow @erqan and refresh page...

**Comment by Erkan-Yilmaz** [comment]
@erqan it works :-) THX

**Comment by slr** [comment]
@erkan can you provide examle of problem post or describe it's content?

**Comment by Erkan-Yilmaz** [comment]
@slr it was one of the posts from the @erqan account

**Comment by slr** [comment]
@erkan I can't see it now. it'd be helpful if you provide 10 last posts or something right here.

**Comment by erqan** [comment]
@slr lack of `msg` field... https://github.com/miguelfreitas/twister-html/blob/master/js/twister_formatpost.js#L69
