### ISSUE TITLE
remove non-working link

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [miguelfreitas/twister-html#300]
see pic below: 
"Followers *"

1. clicking on link does nothing <- irritating for new users
2. until (A) fixed, useless anyways

(A) https://github.com/miguelfreitas/twister-core/issues/11

![bildschirmfoto vom 2015-08-21 15 03 28](https://cloud.githubusercontent.com/assets/642286/9408808/078a50c4-4816-11e5-9677-022d9d158b80.png)

**Comment by slr** [comment]
after clicking in `blaster` branch now:
![example of followers modal with brief explanation of current inability of obtaining of complete followers list](https://i.imgur.com/4Kq9YUW.png)

see https://github.com/miguelfreitas/twister-html/commit/57374638e01d3dd6be70189ae8d63d930cd608f9

**Comment by slr** [comment]
wanna close?

**Comment by Erkan-Yilmaz** [comment]
thanks! closed
