### ISSUE TITLE
show me who I am following privately

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [miguelfreitas/twister-html#302]
Since (1), it'd be great to show myself who I follow in private.

use cases: 
- so I can follow them also in public, after some time. (2)
- or remove them: I guess every subscription makes a regular poll
- when using another browser: I might want to take those private follows with me
- ...

I am not sure what would be better:
- a page with all who I am following privately (e.g. by querying the browser's local storage)
- or only at the other's user page

(1) RT @tasty #private subscriptions stores in local storage of your browser. 
(2) E.g. for new users I do this, so I can react faster on their questions about twister

**Comment by slr** [comment]
open following page and see.

**Comment by Erkan-Yilmaz** [comment]
@slr can you explain more please?
checked with original theme + NIn v2: but I only see the indication "public" nxt to users but not private

**Comment by slr** [comment]
on that page you see both 'public' and 'pivate' peers and they marked accordingly. you able to switch modes by clicking on button.

[example](https://i.imgur.com/PRGEVp9.gif)

**Comment by Erkan-Yilmaz** [comment]
you are right, I see it now

I didn't see it before, 
since I get in FF too many "script taking too long" msgs and I stop those then :-(
In this following page it was the /js/jquery.min.js:2
