### ISSUE TITLE
twister-html timeline broken (when certain msg)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [miguelfreitas/twister-html#313]
RT @denis 
@userstats Your post #1492 breaks twister-html timeline because of undefined msg field (and with an "edit" field)
twister_formatpost.js should be patched to skip such messages

**Comment by slr** [comment]
fixed by https://github.com/slr/twister-html/commit/1afe26afb3ebf0166131fee7265e3adf6675967e

**Comment by slr** [comment]
see miguelfreitas/twister-html#312
