### ISSUE TITLE
No response after "Save Changes"

### ISSUE THREAD

**Issue by xfq** [miguelfreitas/twister-html#317]
After clicking the "Save Changes" button in `profile-edit.html`, I don't see any "response" (such as an `alert("Profile updated successfully")`), so I don't know whether the profile has been updated or not.  Is it a bug in `js/twister_user.js`?

Browser: Google Chrome 46.0.2490.80 on OS X 10.11.1 (Build 15B42), haven't tried other browsers yet

**Comment by slr** [comment]
it isn't a bug, it's a flaw. fixed anyway via https://github.com/miguelfreitas/twister-html/commit/b2e2ba308c08bf62f3f9cc2e1c45d7b9cfa99cf8 and mostly https://github.com/miguelfreitas/twister-html/commit/1d1abd24ad24d124e483ff34e2cc3be40a204d6b in 'blaster' branch.

**Comment by slr** [comment]
![example with fixed menu](https://i.imgur.com/55dc86i.png)

**Comment by xfq** [comment]
@slr Thank you very much!

**Comment by slr** [comment]
@xfq you are welcome.
