### ISSUE TITLE
How to choose between the Desktop and Mobile interfaces?

### ISSUE THREAD

**Issue by xfq** [miguelfreitas/twister-html#323]
In https://github.com/miguelfreitas/twister-core/blob/master/README.md#running-the-web-interface:

> Visit http://user:pwd@localhost:28332 in your web browser and you should see a page asking you to choose between the Desktop and Mobile interfaces.

I didn't see the page asking me to choose interfaces when I visited this URI for the first time.  Screenshot:

<img width="1280" alt="screen shot 2015-11-01 at 12 23 16 pm" src="https://cloud.githubusercontent.com/assets/2863444/11018383/08097adc-8602-11e5-9697-fddecfca0441.png">

I'm using the latest master branch of twister-core and twister-html.  As for browsers, I've tried Firefox 41 on OS X, Google Chrome 46 on OS X, and Google Chrome 46 on iOS.

**Comment by slr** [comment]
open `localhost:28332/index.html` to see that page. currently mobile interface client is located on `localhost:28332/tmobile.html`, in future I hope it will be inlined in desktop version. possibly docs should be changed for now.
