### ISSUE TITLE
Group invite peers requires @ (but no hint is provided) 

### ISSUE THREAD

**Issue by miguelfreitas** [miguelfreitas/twister-html#326]
Inviting peers to join a chat group requires each username to be preceded by @, however no hint is provided to user about this requirement. Trying to invite without @ causes a strange error:

`Can't invite null to *fgdfgdgdfgdgdfg group...`

User is left stuck with the problem.

Of course, this is a issue with `twister_directmsg.js` around line 489:

```
        var peersToInvite = elemInput.val().toLowerCase().match(/@\w+/g);
        if (peersToInvite)
            peersToInvite = peersToInvite.join('').slice(1).split('@');
```

It seems a bit too strict about requiring @. Maybe an alternative syntax with space or comas as separators should be accepted as well.

**Comment by slr** [comment]
example is added to placeholder of invitation form: https://github.com/miguelfreitas/twister-html/commit/3ae58616cfb940bc82d9c00eb0564122509273a9

**Comment by miguelfreitas** [comment]
good idea.
