### ISSUE TITLE
Some features not available in the blaster branch

### ISSUE THREAD

**Issue by ghost** [miguelfreitas/twister-html#387]
For example:

- ~Profile button not showing in the top menu~
- ~/profile-edit.html not found~
- ~Bitmessage and Tox buttons are not available in the profile's view mode~

where can I find more details about the blaster branch state/specification/roadmap?

#386

(latest version, nin theme)

----

**update**

1, 2 - found it, interface elements was moved to the drop down menu.
3 - not displaying as not provided, all is ok.

![2021-04-23_08-56](https://user-images.githubusercontent.com/76843085/115825378-01b5f280-a412-11eb-9763-363a6fc7c2ab.png)

**Comment by slr** [comment]
> where can I find more details about the blaster branch state/specification/roadmap?

I beleive you cannot since it simply doesn't exists in this version of the material world. I used to have some TODO list for myself back in the days when it was less abandoned than it is now, but there is no much of interest in it to be honest.
