### ISSUE TITLE
Allow navigating backwards in DM modal. 

### ISSUE THREAD

**Issue by BlockTester** [miguelfreitas/twister-html#41]
Once you've clicked a user in the DM panel to see a thread, it is no longer possible to come back without closing the panel and re-opening it.

**Comment by Tschaul** [comment]
I created a branch (https://github.com/Tschaul/twister-html/tree/global-back-button-in-modal) where the back button that is currently only visible in the direct messages modal is always visible and controlled by the watchHashChange function. Also i feed all modal navigation trough this function (not complete yet). The back button then works across the different modals (e.g. from a hashtag back to a profile).

Feedback is welcome. I will create a pull request when I'm done.

**Comment by miguelfreitas** [comment]
@Tschaul that's good news you are working on this!

**Comment by slr** [comment]
it's working good for a while so I'm closing issue.
