### ISSUE TITLE
Mixed hashtag when viewing from post.

### ISSUE THREAD

**Issue by BlockTester** [miguelfreitas/twister-html#51]
When you view the timeline of a hashtag, if you've clicked the hashtag from a post that contained more than one hashtag you will get results for all of the tags contained in the post. 

![image](https://f.cloud.github.com/assets/6403056/1937262/fc2ef46c-7f1e-11e3-9f68-d13be5a60837.png)

You can see in this screenshot that while the selected tag is _twist_, messages containing only _twister_ are also displayed as the post on which we clicked contained both of these hashtags,

**Comment by Tschaul** [comment]
I tried a lot to reproduce this bug, but wasn't able to. I'd say with 95% certainty that it is gone. Can someone else try? Or we close it until it reappears.

**Comment by miguelfreitas** [comment]
oh yes, i remember fixing this :-)
