### ISSUE TITLE
Misplaced modal header viewing followings.

### ISSUE THREAD

**Issue by BlockTester** [miguelfreitas/twister-html#52]
On the modal for viewing a user's followings, the header should be pinned on top of the modal but instead it is inside the container; thus scrolling with the container.

![image](https://f.cloud.github.com/assets/6403056/1937273/6928eaf0-7f1f-11e3-830d-b20886a15e5f.png)

![image](https://f.cloud.github.com/assets/6403056/1937274/6b316f16-7f1f-11e3-8b44-b929d3894c07.png)

Expected behavior:

The header should stick on top of the modal.

**Comment by Tschaul** [comment]
Seams resolved, i tested firefox and chromium. Close?
