### ISSUE TITLE
Display new messages indicator in DM threads list

### ISSUE THREAD

**Issue by miguelfreitas** [miguelfreitas/twister-html#94]
Currently we have an indicator for the total number of DMs in top bar. This total, however, is not broken down on individual users shown in DM threads list.

This makes finding the actual new messages kind of difficult. Some indication must be provided and/or users should be sorted by the most recent first.

**Comment by slr** [comment]
indication: https://github.com/miguelfreitas/twister-html/commit/50827a6691829e50b592819ab22168f751e5c23e

**Comment by slr** [comment]
btw messages in DM threads list are sorted in by time descending order, new ones are on top of it. so I'm closing issue.
